steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['ci']
- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'build']
- name: us-central1-docker.pkg.dev/quasar-kim-website/cloudbuild/firebase
  args: ['deploy', '--project=quasar-kim-website', '--only=hosting']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET