steps:
- name: 'node'
  entrypoint: 'npm'
  args: ['ci']
- name: 'node'
  entrypoint: 'npm'
  args: ['run', 'build']
- name: gcr.io/quasar-kim-website/firebase
  args: ['deploy', '--project=personal-website-aa692', '--only=hosting']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET